#ifndef GAUGE_TYPES_H
#define GAUGE_TYPES_H

#ifdef __cplusplus
extern "C" {
#endif

// Data source gauge types (for persistent history)
typedef enum {
	POWER_MONITOR_DATA_STARTER_VOLTAGE = 0,
	POWER_MONITOR_DATA_STARTER_CURRENT,
	POWER_MONITOR_DATA_HOUSE_VOLTAGE,
	POWER_MONITOR_DATA_HOUSE_CURRENT,
	POWER_MONITOR_DATA_SOLAR_VOLTAGE,
	POWER_MONITOR_DATA_SOLAR_CURRENT,
	POWER_MONITOR_DATA_COUNT
} power_monitor_data_type_t;

// Power monitor gauge instance types - each gauge instance has a unique ID
typedef enum {
	// Detail view gauges
	POWER_MONITOR_GAUGE_DETAIL_STARTER_VOLTAGE = 0,
	POWER_MONITOR_GAUGE_DETAIL_STARTER_CURRENT,
	POWER_MONITOR_GAUGE_DETAIL_HOUSE_VOLTAGE,
	POWER_MONITOR_GAUGE_DETAIL_HOUSE_CURRENT,
	POWER_MONITOR_GAUGE_DETAIL_SOLAR_VOLTAGE,
	POWER_MONITOR_GAUGE_DETAIL_SOLAR_CURRENT,

	// Power grid view gauges (current_view)
	POWER_MONITOR_GAUGE_GRID_STARTER_VOLTAGE,
	POWER_MONITOR_GAUGE_GRID_HOUSE_VOLTAGE,
	POWER_MONITOR_GAUGE_GRID_SOLAR_VOLTAGE,

	// Single view gauge (current_view)
	POWER_MONITOR_GAUGE_SINGLE_STARTER_VOLTAGE,

	POWER_MONITOR_GAUGE_COUNT
} power_monitor_gauge_type_t;

#ifdef __cplusplus
}
#endif

#endif // GAUGE_TYPES_H
